#!/usr/bin/env bash
# shellcheck disable=SC2086
# Function to display subdomain information
display_info() {
    local domain=$1
    local subdomain=$2

    if [[ -z $subdomain ]]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        record=$(dig +short $sub.$domain)
        record_type=$(dig +short $sub.$domain | awk '{print $1}')

        echo "The subdomain $sub is a $record_type record and points to $record"
    done
}

# Main script
if [[ $# -eq 1 ]]; then
    display_info $1
elif [[ $# -eq 2 ]]; then
    display_info $1 $2
else
    echo "Invalid number of arguments. Usage: $0 domain [subdomain]"
fi
