#!/usr/bin/env bash
# Check if number of arguments is less than 4
if [ "$#" -lt 4 ];
then
# Function to display usage
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
# Transfer file using scp to the server's home directory
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/;
fi
