#!/usr/bin/env bash
# Update repositories and install nginx on the server
apt update
apt install nginx -y

# Create new index file
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# Configure Nginx to listen on port 80
#config_file="/etc/nginx/sites-available/default"
#sed -i 's/^listen\s*80;/listen 80;/g' "$config_file"

# Add redirection configuration to Nginx
echo '
server {
    listen 80;
    server_name localhost;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
    }
}' > /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
