#!/usr/bin/env bash
# Bash script that pings an IP address passed as an argument

# Check for exavtly one argument
if [ "$#" -ne 1 ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit 1
fi

# Get IP address from the command line argument
ip_address="$1"

# Pint 5 times
ping -c 5 "$ip_address"
