#!/usr/bin/env bash
# Bash script that displays the content of the file "/etc/passwd"

# Loop through /etc/passwd line by line
while IFS=: read -r username _ userid _ _ _ home_directory _
do
	# Print: username, user ID, and home directory
	echo "$username:$userid:$home_directory"
done < /etc/passwd
