#!/usr/bin/env bash

# Bash script that displays the content of the file "/etc/passwd"

# Loop through /etc/passwd line by line
while IFS=: read -r username password userid uid gid description home_directory shell
do
	# Print: username, user ID, and home directory
	message="The user $username is part of the group $gid gang, lives in $home_directory and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $uid"
	echo "$message"
done < /etc/passwd
