#!/usr/bin/env bash
# Bash script that displays number from 1 to 20 using a while loop
# At number 4 "bad luck from China" is displayed after the number
# At number 9 "bad luck from China" is displayed after the number
# At number 17 "bad luck from Italy" is displayed after the number

i=1

while [ $i -le 20 ]
do
	case $i in
		4)
			echo $i
			echo "bad luck from China"
			;;
		9)
			echo $i
			echo "bad luck from Japan"
			;;
		17)
			echo $i
			echo "bad luck from Italy"
			;;
		*)
			echo $i
			;;
	esac
	(( i++ ))
done
